version: "3"

services:
  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root      
      MYSQL_USER: root
      MYSQL_DATABASE: root      
    ports:
      - "3306:3306"
